-- Website logo configuration — now stored in Firebase, no MySQL changes
-- are required for the logo itself.
--
-- Active logo configuration: Firestore document `settings/website`:
--   settings/website = {
--     logoUrl:   "https://firebasestorage.googleapis.com/v0/b/.../website/logo/active-logo-....png?alt=media",
--     logoPath:  "website/logo/active-logo-....png",
--     fileName:  "original-name.png",
--     width:     1536,
--     height:    683,
--     updatedAt: <server timestamp>,
--     updatedBy: "<Firebase UID of the admin>"
--   }
--
-- Logo image files: Firebase Storage under `website/logo/` (download URLs
-- are public-read; writes happen only through the server-side admin flow
-- in /api/logo, which verifies the caller against the MySQL `admins`
-- table — see below).
--
-- Admin accounts: the MySQL `admins` table is the single source of truth
-- for who may change the logo. If it does not exist yet:
--
--   CREATE TABLE IF NOT EXISTS admins (
--     uid VARCHAR(191) NOT NULL PRIMARY KEY,
--     email VARCHAR(255) NULL,
--     display_name VARCHAR(255) NULL,
--     created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
--   ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
--   INSERT INTO admins (uid, email, display_name) VALUES
--     ('FIREBASE_UID', 'admin@example.com', 'Admin Name');
--
-- The Firestore and Storage security rules (firestore.rules,
-- storage.rules) keep every client read-only for logo data — clients can
-- never upload or change the website logo.